export const SD_LOAD_REQUEST = 'SD_LOAD_REQUEST';
export const SD_LOAD_REQUEST_FAIL = 'SD_LOAD_REQUEST_FAIL';
export const SD_LOAD_REQUEST_SUCCESS = 'SD_LOAD_REQUEST_SUCCESS';

export const SD_PUT_REQUEST = 'SD_PUT_REQUEST';
export const SD_PUT_REQUEST_FAIL = 'SD_PUT_REQUEST_FAIL';
export const SD_PUT_REQUEST_SUCCESS = 'SD_PUT_REQUEST_SUCCESS';