export const ROOMSD_LOAD_REQUEST = 'ROOMSD_LOAD_REQUEST';
export const ROOMSD_LOAD_REQUEST_FAIL = 'ROOMSD_LOAD_REQUEST_FAIL';
export const ROOMSD_LOAD_REQUEST_SUCCESS = 'ROOMSD_LOAD_REQUEST_SUCCESS';